### ISSUE TITLE
Stream notifications need to have a custom message to work

### ISSUE THREAD

**Issue by InjuredWolf** [devakira/twitchbot#5]
![image](https://user-images.githubusercontent.com/10350531/41400907-bace3b12-7001-11e8-9285-ee7f3dd43b58.png)
the bot can see my channel when looking up the user, but not when trying to set up the live notification for it

**Comment by devakira** [comment]
If you add a custom message after the command like `twitch notif add #channel kraken Hey @everyone, kraken is now streaming!` it should work. It's a bug where you can't add the person unless there's a custom message.

**Comment by devakira** [comment]
Fixed in latest patch.
